// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.4
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1621

#include "LoggerI.h"

// Implementation skeleton constructor
Logger_i::Logger_i (){}

// Implementation skeleton destructor
Logger_i::~Logger_i (){}

void Logger_i::log (
  ::Severidade s,
  const std::string endereco,
  ::CORBA::UShort pid,
  ::CORBA::ULongLong hora,
  const std::string msg){
  // Add your implementation here
  	std :: cont << "[log] serv: " << s
	  			<< "endereco:   " <<endereco
	  			<< "pid: 	    " << pid
	  			<< "hora:       " << hora
	  			<< "msg:        " << mgs << std :: endl;
	  			
	ultimo_endereco[s] = endereco; 
}

std::string Logger_i::locate (
  ::Severidade s){
  // Add your implementation here
  auto posicao = ultimo_endereco.find(s);
  if (posicao == ultimo_endereco.end())
  {
  	throw EventoNaoRecebido();
  }
  return posicao -> second;
}